# Generated by Django 6.1.1 on 2026-09-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('rama', models.CharField(choices=[('MIXTO', 'Mixto'), ('DAMAS', 'Damas'), ('VARONES', 'Varones')], max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReglaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_min', models.PositiveSmallIntegerField()),
                ('edad_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temporada', models.PositiveSmallIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas', to='usuarios.categoria')),
            ],
            options={
                'verbose_name': 'regla de categoría',
                'verbose_name_plural': 'reglas de categorías',
                'ordering': ['temporada', 'edad_min', 'categoria_id'],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'temporada'), name='unique_categoria_temporada'), models.CheckConstraint(condition=models.Q(('edad_max__isnull', True), ('edad_max__gte', models.F('edad_min')), _connector='OR'), name='edad_max_mayor_igual_edad_min')],
            },
        ),
    ]
