# Generated by Django 6.1.1 on 2026-09-18 10:40

import django.db.models.deletion
import usuarios.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_categoria_reglacategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[usuarios.validators.validar_rut])),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('rama', models.CharField(choices=[('DAMAS', 'Damas'), ('VARONES', 'Varones')], max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='PENDIENTE', max_length=10)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('procedencia', models.CharField(choices=[('INDEPENDIENTE', 'Independiente'), ('OTRO_CLUB', 'Otro club')], default='INDEPENDIENTE', max_length=20)),
                ('club_anterior', models.CharField(blank=True, max_length=150)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='usuarios.categoria')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'jugador',
                'verbose_name_plural': 'jugadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
