# Generated by Django 6.1.1 on 2026-09-19 08:23

import django.db.models.deletion
import usuarios.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[usuarios.validators.validar_rut])),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apoderado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'apoderado',
                'verbose_name_plural': 'apoderados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
