# Generated by Django 6.1.1 on 2026-09-19 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_apoderado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoderadoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=50)),
                ('es_principal', models.BooleanField(default=False)),
                ('puede_gestionar', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_jugadores', to='usuarios.apoderado')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_apoderados', to='usuarios.jugador')),
            ],
            options={
                'verbose_name': 'relacion apoderado-jugador',
                'verbose_name_plural': 'relaciones apoderado-jugador',
                'constraints': [models.UniqueConstraint(fields=('apoderado', 'jugador'), name='unique_apoderado_jugador')],
            },
        ),
    ]
