# Generated by Django 6.1.1 on 2026-09-19 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_apoderadojugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revision'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('procedencia', models.CharField(choices=[('INDEPENDIENTE', 'Independiente'), ('OTRO_CLUB', 'Otro club')], max_length=20)),
                ('club_anterior', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('consentimiento', models.BooleanField(default=False)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_inscripcion', to='usuarios.jugador')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de inscripcion',
                'verbose_name_plural': 'solicitudes de inscripcion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
