# Generated by Django 6.1.1 on 2026-09-19 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_solicitudinscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_salud', to='usuarios.jugador')),
            ],
            options={
                'verbose_name': 'alerta de salud',
                'verbose_name_plural': 'alertas de salud',
                'ordering': ['-activa', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('AUTOMATICO', 'Automatico'), ('EXCEPCION_MANUAL', 'Excepcion manual'), ('CAMBIO_TEMPORADA', 'Cambio de temporada')], max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_categoria_realizados', to=settings.AUTH_USER_MODEL)),
                ('categoria_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_como_anterior', to='usuarios.categoria')),
                ('categoria_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_como_nueva', to='usuarios.categoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_categorias', to='usuarios.jugador')),
            ],
            options={
                'verbose_name': 'historial de categoria',
                'verbose_name_plural': 'historiales de categorias',
                'ordering': ['-fecha'],
            },
        ),
    ]
