# Generated by Django 6.1.1 on 2026-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='nombre_contacto_emergencia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='jugador',
            name='telefono_contacto_emergencia',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
