# Generated by Django 6.1.1 on 2026-09-30 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_jugador_nombre_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='jugador',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='solicitudinscripcion',
            name='usuario_autorizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_autorizadoras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
