# Generated by Django 6.1.1 on 2026-10-03 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0008_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrenamientos', to='usuarios.categoria')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrenamientos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado')], default='PRESENTE', max_length=20)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('motivo_modificacion', models.TextField(blank=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='usuarios.jugador')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='deportivo.entrenamiento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entrenamiento', 'jugador'), name='asistencia_unica_por_asistencia')],
            },
        ),
    ]
