# Generated by Django 6.1.1 on 2026-10-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportivo', '0002_perfilentrenador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenamiento',
            options={'ordering': ['-fecha', '-creado_en']},
        ),
    ]
